
from PyQt5 import QtCore, QtGui, QtWidgets
#import I2Cardu2
import math
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.Start_Display = QtWidgets.QWidget()
        self.Start_Display.setObjectName("Start_Display")
        self.label = QtWidgets.QLabel(self.Start_Display)
        self.label.setGeometry(QtCore.QRect(360, 140, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.Start_Display)
        self.line.setGeometry(QtCore.QRect(350, 200, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.Start_Display)
        self.label_2.setGeometry(QtCore.QRect(430, 240, 201, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../.designer/backup/Downloads/WhatsApp Image 2021-02-24 at 11.20.52.jpeg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Start_Display)
        self.label_3.setGeometry(QtCore.QRect(370, 450, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Start_Display)
        self.label_4.setGeometry(QtCore.QRect(220, 20, 591, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../.designer/backup/Documents/coding/Rumpiang_GUI_V0/Logo Gundala1.png"))
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.Start_Display)
        self.label_11.setGeometry(QtCore.QRect(210, 50, 611, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Logo Gundala1.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Start_Display)
        self.label_12.setGeometry(QtCore.QRect(410, 220, 271, 221))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Logo Charger Mobil.jpeg"))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.Start_Display, "")
        self.Setting_Display = QtWidgets.QWidget()
        self.Setting_Display.setObjectName("Setting_Display")
        self.label_5 = QtWidgets.QLabel(self.Setting_Display)
        self.label_5.setGeometry(QtCore.QRect(930, 490, 81, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../.designer/backup/Downloads/WhatsApp Image 2021-02-24 at 11.20.52.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.Setting_Display)
        self.line_2.setGeometry(QtCore.QRect(0, 66, 711, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Setting_Display_Widget = QtWidgets.QWidget(self.Setting_Display)
        self.Setting_Display_Widget.setGeometry(QtCore.QRect(720, 0, 301, 431))
        self.Setting_Display_Widget.setObjectName("Setting_Display_Widget")
        self.Current_State_Battery = QtWidgets.QProgressBar(self.Setting_Display_Widget)
        self.Current_State_Battery.setGeometry(QtCore.QRect(100, 70, 111, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current_State_Battery.sizePolicy().hasHeightForWidth())
        self.Current_State_Battery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        self.Current_State_Battery.setFont(font)
        self.Current_State_Battery.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Current_State_Battery.setAutoFillBackground(True)
        self.Current_State_Battery.setProperty("value", 24)
        self.Current_State_Battery.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Current_State_Battery.setTextVisible(True)
        self.Current_State_Battery.setOrientation(QtCore.Qt.Vertical)
        self.Current_State_Battery.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Current_State_Battery.setObjectName("Current_State_Battery")
        self.label_10 = QtWidgets.QLabel(self.Setting_Display_Widget)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_3 = QtWidgets.QFrame(self.Setting_Display)
        self.line_3.setGeometry(QtCore.QRect(700, 0, 20, 571))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_6 = QtWidgets.QLabel(self.Setting_Display)
        self.label_6.setGeometry(QtCore.QRect(170, 10, 331, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../../.designer/backup/Documents/coding/Rumpiang_GUI_V0/Logo Gundala1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Setting_Display)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.kWh_Button = QtWidgets.QPushButton(self.Setting_Display)
        self.kWh_Button.setGeometry(QtCore.QRect(210, 80, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kWh_Button.setFont(font)
        self.kWh_Button.setObjectName("kWh_Button")
        self.Rupiah_Button = QtWidgets.QPushButton(self.Setting_Display)
        self.Rupiah_Button.setGeometry(QtCore.QRect(470, 80, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rupiah_Button.setFont(font)
        self.Rupiah_Button.setObjectName("Rupiah_Button")
        self.widget_2 = QtWidgets.QWidget(self.Setting_Display)
        self.widget_2.setGeometry(QtCore.QRect(0, 130, 701, 421))
        self.widget_2.setObjectName("widget_2")
        self.kWh_Label = QtWidgets.QLabel(self.widget_2)
        self.kWh_Label.setGeometry(QtCore.QRect(10, 0, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kWh_Label.setFont(font)
        self.kWh_Label.setScaledContents(True)
        self.kWh_Label.setObjectName("kWh_Label")
        self.Amount_LineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.Amount_LineEdit.setGeometry(QtCore.QRect(150, 10, 161, 41))
        self.Amount_LineEdit.setObjectName("Amount_LineEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 301, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Angka_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_3.setFont(font)
        self.Angka_3.setObjectName("Angka_3")
        self.gridLayout.addWidget(self.Angka_3, 0, 2, 1, 1)
        self.Angka_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_4.setFont(font)
        self.Angka_4.setObjectName("Angka_4")
        self.gridLayout.addWidget(self.Angka_4, 1, 0, 1, 1)
        self.Angka_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_9.setFont(font)
        self.Angka_9.setObjectName("Angka_9")
        self.gridLayout.addWidget(self.Angka_9, 2, 2, 1, 1)
        self.Angka_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_2.setFont(font)
        self.Angka_2.setObjectName("Angka_2")
        self.gridLayout.addWidget(self.Angka_2, 0, 1, 1, 1)
        self.Angka_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_5.setFont(font)
        self.Angka_5.setObjectName("Angka_5")
        self.gridLayout.addWidget(self.Angka_5, 1, 1, 1, 1)
        self.Angka_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_1.setFont(font)
        self.Angka_1.setObjectName("Angka_1")
        self.gridLayout.addWidget(self.Angka_1, 0, 0, 1, 1)
        self.Angka_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_6.setFont(font)
        self.Angka_6.setObjectName("Angka_6")
        self.gridLayout.addWidget(self.Angka_6, 1, 2, 1, 1)
        self.Angka_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_7.setFont(font)
        self.Angka_7.setObjectName("Angka_7")
        self.gridLayout.addWidget(self.Angka_7, 2, 0, 1, 1)
        self.Angka_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Angka_8.sizePolicy().hasHeightForWidth())
        self.Angka_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_8.setFont(font)
        self.Angka_8.setObjectName("Angka_8")
        self.gridLayout.addWidget(self.Angka_8, 2, 1, 1, 1)
        self.Angka_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angka_0.setFont(font)
        self.Angka_0.setObjectName("Angka_0")
        self.gridLayout.addWidget(self.Angka_0, 3, 1, 1, 1)
        self.Enter_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Enter_Button.setFont(font)
        self.Enter_Button.setObjectName("Enter_Button")
        self.gridLayout.addWidget(self.Enter_Button, 3, 2, 1, 1)
        self.Clear_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Clear_Button.setFont(font)
        self.Clear_Button.setObjectName("Clear_Button")
        self.gridLayout.addWidget(self.Clear_Button, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(10, 330, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Speed_Combo = QtWidgets.QComboBox(self.widget_2)
        self.Speed_Combo.setGeometry(QtCore.QRect(10, 370, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Speed_Combo.setFont(font)
        self.Speed_Combo.setObjectName("Speed_Combo")
        self.Speed_Combo.addItem("")
        self.Speed_Combo.addItem("")
        self.Speed_Combo.addItem("")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(360, 20, 341, 341))
        self.widget_3.setObjectName("widget_3")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(120, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 321, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Value_Ampere = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Value_Ampere.setFont(font)
        self.Value_Ampere.setObjectName("Value_Ampere")
        self.gridLayout_2.addWidget(self.Value_Ampere, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 2, 1, 1)
        self.Value_Rupiah = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Value_Rupiah.setFont(font)
        self.Value_Rupiah.setObjectName("Value_Rupiah")
        self.gridLayout_2.addWidget(self.Value_Rupiah, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.Value_kWh = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Value_kWh.setFont(font)
        self.Value_kWh.setObjectName("Value_kWh")
        self.gridLayout_2.addWidget(self.Value_kWh, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 0, 1, 1)
        self.Value_Hour = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Value_Hour.setFont(font)
        self.Value_Hour.setObjectName("Value_Hour")
        self.gridLayout_2.addWidget(self.Value_Hour, 3, 1, 1, 1)
        self.Value_Minute = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Value_Minute.setFont(font)
        self.Value_Minute.setObjectName("Value_Minute")
        self.gridLayout_2.addWidget(self.Value_Minute, 3, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.widget_3)
        self.line_7.setGeometry(QtCore.QRect(110, 40, 118, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Ok_Button = QtWidgets.QPushButton(self.widget_2)
        self.Ok_Button.setGeometry(QtCore.QRect(460, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Ok_Button.setFont(font)
        self.Ok_Button.setObjectName("Ok_Button")
        self.Start_Charging = QtWidgets.QPushButton(self.Setting_Display)
        self.Start_Charging.setGeometry(QtCore.QRect(740, 510, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Start_Charging.setFont(font)
        self.Start_Charging.setObjectName("Start_Charging")
        self.line_4 = QtWidgets.QFrame(self.Setting_Display)
        self.line_4.setGeometry(QtCore.QRect(710, 480, 311, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(self.Setting_Display)
        self.label_13.setGeometry(QtCore.QRect(140, 0, 411, 71))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Logo Gundala1.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Setting_Display)
        self.label_14.setGeometry(QtCore.QRect(930, 490, 81, 71))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Logo Charger Mobil.jpeg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.line_5 = QtWidgets.QFrame(self.Setting_Display)
        self.line_5.setGeometry(QtCore.QRect(0, 110, 711, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.Setting_Display)
        self.line_6.setGeometry(QtCore.QRect(353, 120, 20, 451))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_8 = QtWidgets.QLabel(self.Setting_Display)
        self.label_8.setGeometry(QtCore.QRect(720, 440, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.Value_Battery_Temperature = QtWidgets.QLCDNumber(self.Setting_Display)
        self.Value_Battery_Temperature.setGeometry(QtCore.QRect(820, 440, 121, 41))
        self.Value_Battery_Temperature.setObjectName("Value_Battery_Temperature")
        self.label_9 = QtWidgets.QLabel(self.Setting_Display)
        self.label_9.setGeometry(QtCore.QRect(950, 440, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.Setting_Display, "")
        self.Charging_Display = QtWidgets.QWidget()
        self.Charging_Display.setObjectName("Charging_Display")
        self.Charging_Display_Widget = QtWidgets.QWidget(self.Charging_Display)
        self.Charging_Display_Widget.setGeometry(QtCore.QRect(560, 0, 461, 421))
        self.Charging_Display_Widget.setObjectName("Charging_Display_Widget")
        self.Charged_Battery = QtWidgets.QProgressBar(self.Charging_Display_Widget)
        self.Charged_Battery.setGeometry(QtCore.QRect(180, 60, 111, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Charged_Battery.sizePolicy().hasHeightForWidth())
        self.Charged_Battery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        self.Charged_Battery.setFont(font)
        self.Charged_Battery.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Charged_Battery.setAutoFillBackground(True)
        self.Charged_Battery.setProperty("value", 24)
        self.Charged_Battery.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Charged_Battery.setTextVisible(True)
        self.Charged_Battery.setOrientation(QtCore.Qt.Vertical)
        self.Charged_Battery.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Charged_Battery.setObjectName("Charged_Battery")
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_25 = QtWidgets.QLabel(self.Charging_Display_Widget)
        self.label_25.setGeometry(QtCore.QRect(140, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_31 = QtWidgets.QLabel(self.Charging_Display)
        self.label_31.setGeometry(QtCore.QRect(940, 500, 71, 61))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("Logo Charger Mobil.jpeg"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.Stop_Charging = QtWidgets.QPushButton(self.Charging_Display)
        self.Stop_Charging.setGeometry(QtCore.QRect(670, 510, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Stop_Charging.setFont(font)
        self.Stop_Charging.setObjectName("Stop_Charging")
        self.label_29 = QtWidgets.QLabel(self.Charging_Display)
        self.label_29.setGeometry(QtCore.QRect(610, 430, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_29.setFont(font)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.Value_Battery_Temperature_2 = QtWidgets.QLCDNumber(self.Charging_Display)
        self.Value_Battery_Temperature_2.setGeometry(QtCore.QRect(730, 430, 121, 41))
        self.Value_Battery_Temperature_2.setObjectName("Value_Battery_Temperature_2")
        self.label_30 = QtWidgets.QLabel(self.Charging_Display)
        self.label_30.setGeometry(QtCore.QRect(880, 430, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.line_8 = QtWidgets.QFrame(self.Charging_Display)
        self.line_8.setGeometry(QtCore.QRect(542, 0, 21, 571))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.progressBar = QtWidgets.QProgressBar(self.Charging_Display)
        self.progressBar.setGeometry(QtCore.QRect(20, 140, 501, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line_9 = QtWidgets.QFrame(self.Charging_Display)
        self.line_9.setGeometry(QtCore.QRect(0, 80, 551, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_32 = QtWidgets.QLabel(self.Charging_Display)
        self.label_32.setGeometry(QtCore.QRect(80, 10, 401, 71))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("Logo Gundala1.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.Charging_Display)
        self.label_33.setGeometry(QtCore.QRect(220, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Charging_Display)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 230, 441, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout.addWidget(self.label_34)
        self.Val_Hour_Time_Remain = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Val_Hour_Time_Remain.setFont(font)
        self.Val_Hour_Time_Remain.setObjectName("Val_Hour_Time_Remain")
        self.horizontalLayout.addWidget(self.Val_Hour_Time_Remain)
        self.Val_Minute_Time_Remain = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Val_Minute_Time_Remain.setFont(font)
        self.Val_Minute_Time_Remain.setObjectName("Val_Minute_Time_Remain")
        self.horizontalLayout.addWidget(self.Val_Minute_Time_Remain)
        self.line_10 = QtWidgets.QFrame(self.Charging_Display)
        self.line_10.setGeometry(QtCore.QRect(0, 490, 551, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Back_Button = QtWidgets.QPushButton(self.Charging_Display)
        self.Back_Button.setGeometry(QtCore.QRect(90, 510, 121, 41))
        self.Back_Button.setObjectName("Back_Button")
        self.Home_Button = QtWidgets.QPushButton(self.Charging_Display)
        self.Home_Button.setGeometry(QtCore.QRect(360, 510, 111, 41))
        self.Home_Button.setObjectName("Home_Button")
        self.label_37 = QtWidgets.QLabel(self.Charging_Display)
        self.label_37.setGeometry(QtCore.QRect(150, 360, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.Status_Charge = QtWidgets.QLabel(self.Charging_Display)
        self.Status_Charge.setGeometry(QtCore.QRect(250, 350, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Status_Charge.setFont(font)
        self.Status_Charge.setObjectName("Status_Charge")
        self.line_11 = QtWidgets.QFrame(self.Charging_Display)
        self.line_11.setGeometry(QtCore.QRect(550, 490, 471, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.tabWidget.addTab(self.Charging_Display, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Charging Terminal Mobil Listrik "))
        self.label_3.setText(_translate("MainWindow", "Terminal dan Suplai daya Meter Untuk Pengisian baterai mobil Listrik"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Start_Display), _translate("MainWindow", "Start Display"))
        self.label_10.setText(_translate("MainWindow", "Current State Battery"))
        self.label_7.setText(_translate("MainWindow", "Charged By :"))
        self.kWh_Button.setText(_translate("MainWindow", "kWh"))
        self.kWh_Button.clicked.connect(self.kwh_Button)
        self.Rupiah_Button.setText(_translate("MainWindow", "Rupiah"))
        self.Rupiah_Button.clicked.connect(self.rupiah_Button)
        self.kWh_Label.setText(_translate("MainWindow", "Amount kWh"))
        self.Angka_0.setText(_translate("MainWindow", "0"))
        self.Angka_0.clicked.connect(lambda: self.write_digit(0))
        self.Angka_1.setText(_translate("MainWindow", "1"))
        self.Angka_1.clicked.connect(lambda: self.write_digit(1))
        self.Angka_2.setText(_translate("MainWindow", "2"))
        self.Angka_2.clicked.connect(lambda: self.write_digit(2))
        self.Angka_3.setText(_translate("MainWindow", "3"))
        self.Angka_3.clicked.connect(lambda: self.write_digit(3))
        self.Angka_4.setText(_translate("MainWindow", "4"))
        self.Angka_4.clicked.connect(lambda: self.write_digit(4))
        self.Angka_5.setText(_translate("MainWindow", "5"))
        self.Angka_5.clicked.connect(lambda: self.write_digit(5))
        self.Angka_6.setText(_translate("MainWindow", "6"))
        self.Angka_6.clicked.connect(lambda: self.write_digit(6))
        self.Angka_7.setText(_translate("MainWindow", "7"))
        self.Angka_7.clicked.connect(lambda: self.write_digit(7))
        self.Angka_8.setText(_translate("MainWindow", "8"))
        self.Angka_8.clicked.connect(lambda: self.write_digit(8))
        self.Angka_9.setText(_translate("MainWindow", "9"))
        self.Angka_9.clicked.connect(lambda: self.write_digit(9))
        self.Enter_Button.setText(_translate("MainWindow", "Enter"))
        self.Enter_Button.clicked.connect(self.enter_Button)
        self.Clear_Button.setText(_translate("MainWindow", "Clear"))
        self.Clear_Button.clicked.connect(self.Amount_LineEdit.clear)
        self.label_15.setText(_translate("MainWindow", "Select Speed :"))
        self.Speed_Combo.setItemText(0, _translate("MainWindow", "..."))
        self.Speed_Combo.setItemText(1, _translate("MainWindow", "16 A"))
        self.Speed_Combo.setItemText(2, _translate("MainWindow", "32 A"))
        self.Speed_Combo.activated[str].connect(self.configure_current)
        self.label_16.setText(_translate("MainWindow", "Summary :"))
        self.Value_Ampere.setText(_translate("MainWindow", "          0"))
        self.label_22.setText(_translate("MainWindow", "Ampere"))
        self.Value_Rupiah.setText(_translate("MainWindow", "          0"))
        self.label_24.setText(_translate("MainWindow", "Rupiah"))
        self.label_19.setText(_translate("MainWindow", "kWh"))
        self.label_17.setText(_translate("MainWindow", "Amount kWh       :"))
        self.Value_kWh.setText(_translate("MainWindow", "          0"))
        self.label_20.setText(_translate("MainWindow", "Current Charge  :"))
        self.label_23.setText(_translate("MainWindow", "Total Cost             :"))
        self.label_26.setText(_translate("MainWindow", "Estimation Time :"))
        self.Value_Hour.setText(_translate("MainWindow", "    0 Hours"))
        self.Value_Minute.setText(_translate("MainWindow", "  0 Minutes"))
        self.Ok_Button.setText(_translate("MainWindow", "OK"))
        self.Ok_Button.clicked.connect(self.ok_button)
        self.Start_Charging.setText(_translate("MainWindow", "Start Charging"))
        self.Start_Charging.setEnabled(False)
        self.Start_Charging.clicked.connect(self.Start_Charge)
        self.label_8.setText(_translate("MainWindow", "Available Energy"))
        self.label_9.setText(_translate("MainWindow", "kWh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting_Display), _translate("MainWindow", "Setting Display"))
        self.label_25.setText(_translate("MainWindow", "Charged Battery"))
        self.Stop_Charging.setText(_translate("MainWindow", "Stop Charging"))
        self.Stop_Charging.clicked.connect(self.Stop_Charge)
        self.label_29.setText(_translate("MainWindow", "Transmitted Energy"))
        self.label_30.setText(_translate("MainWindow", "kWh"))
        self.label_33.setText(_translate("MainWindow", "Progress :"))
        self.label_34.setText(_translate("MainWindow", "Time Remaining :"))
        self.Val_Hour_Time_Remain.setText(_translate("MainWindow", "      0 hours"))
        self.Val_Minute_Time_Remain.setText(_translate("MainWindow", "      0 minutes"))
        self.Back_Button.setText(_translate("MainWindow", "Back"))
        self.Back_Button.clicked.connect(self.Back_button)
        self.Home_Button.setText(_translate("MainWindow", "Home"))
        self.Home_Button.clicked.connect(self.Home_button)
        self.label_37.setText(_translate("MainWindow", "Status :"))
        self.Status_Charge.setText(_translate("MainWindow", "Incomplete !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Charging_Display), _translate("MainWindow", "Charging Display"))

        #====set Initial Condition=====
        #self.Current_State_Battery.setProperty('value',I2Cardu2.main())
        self.Current_State_Battery.setProperty('value',75)
        self.progressBar.setProperty('value',0)
        #self.Charged_Battery.setProperty('value', I2Cardu2.main())
        self.Charged_Battery.setProperty('value', 75)
        self.Value_Battery_Temperature.setProperty('value', 75)

        #=====Constant
        self.kwh = 1
        self.Rupiah = 0
        self.price = 1500
        self.Voltage = 220
        self.Stop_charge = False

    def rupiah_Button(self):
        self.kwh = 0
        self.Rupiah = 1
        self.kWh_Label.setText('Rupiah')
        self.Amount_LineEdit.clear()
        
    def kwh_Button(self):
        self.kwh = 1
        self.Rupiah = 0
        self.kWh_Label.setText('kWh')
        self.Amount_LineEdit.clear()

    def write_digit(self, digit):
        if digit in range(0,10):
            self.Amount_LineEdit.setText(self.Amount_LineEdit.text()+ str(digit))
    
    def enter_Button(self,text):
        if self.kwh == 1:
            self.Value_kWh.setText(self.Amount_LineEdit.text())
            self.configure_current(text)
        elif self.Rupiah == 1:
            self.Value_kWh.setText(self.kwh_Rupiah(self.Amount_LineEdit.text()))
            self.configure_current(text)
        self.Value_Rupiah.setText(self.TotalCost())
        
    def kwh_Rupiah(self, value):
        if self.kwh == 1:
            value = self.Amount_LineEdit.text()
            return(value)
        elif self.Rupiah == 1:
            value = int(self.Amount_LineEdit.text())/self.price
            return(str(value))
    
    def configure_current(self, text):
        factor_32 = 1.25
        if text == '16 A':
            self.Value_Ampere.setText('16')
            self.Value_Minute.setText(self.Calculate_Estimate_Time()[0]+' minutes')
            self.Value_Hour.setText(self.Calculate_Estimate_Time()[1]+' hours')           
        elif text == '32 A':
            self.Value_Ampere.setText('32')
            self.New_Cost = float(self.TotalCost())*factor_32
            self.New_Cost = str(self.New_Cost)
            self.Value_Rupiah.setText(self.New_Cost)
            self.Value_Minute.setText(self.Calculate_Estimate_Time()[0]+' minutes')
            self.Value_Hour.setText(self.Calculate_Estimate_Time()[1]+' hours')
              
    def ok_button(self):
        self.Start_Charging.setEnabled(True)
    
        
    def TotalCost(self):
        Total = float(self.Value_kWh.text())*self.price
        Total = str(Total)
        return(Total)

    def Calculate_Estimate_Time(self):
        self.Time = (float(self.Value_kWh.text())*1000)/(float(self.Value_Ampere.text())*self.Voltage)

        minute, hour = math.modf(self.Time)

        hour = round(hour)
        minute = minute*60
        minute = round(minute)

        hour = str(hour)
        minute = str(minute)
       
        return([minute, hour])

    def Stop_Charge(self):
        self.Stop_charge = True

    def Start_Charge(self):
        self.tabWidget.setCurrentIndex(2)
        p = 75
        l = 0
        t = 50
        kwh = float(self.Value_kWh.text())
        kwh_start = 0
        kwh_step = kwh/50
        while self.Stop_charge == False:
            self.Charged_Battery.setProperty('value',p)
            self.progressBar.setProperty('value',l)
            self.Val_Minute_Time_Remain.setText(str(t)+' minutes')
            self.Value_Battery_Temperature_2.setProperty('value', kwh_start)
            l = l + 2
            p = p + 0.5
            t = t - 1
            kwh_start = kwh_start + kwh_step
            time.sleep(1)
            if l > 100 or self.Stop_charge == True:
                self.Status_Charge.setText('Charge Complete')
                break
        
        
    
    
    def Home_button(self):
        self.tabWidget.setCurrentIndex(0)

    def Back_button(self):
        self.tabWidget.setCurrentIndex(1)

        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

